# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Picme' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Picme
pod 'Alamofire', '~> 5.4'
pod 'Kingfisher', '~> 6.0'
pod 'SwiftLint'
pod 'SwiftyJSON'
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'    # 사용자 인증
pod 'KakaoSDKUser'    # 카카오 로그인, 사용자 관리
pod 'GoogleSignIn'    # 구글 로그인

  target 'PicmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PicmeUITests' do
    # Pods for testing
  end

end
